#!/usr/bin/env bash
website=$1
case $website in 
    hdwallpapers | simpledesktop | wallhaven) cd /Volumes/Transcend/Code/spd && scrapy crawl $website && cd - >/dev/null;;
    *) echo -e "usage: spdstart website_name \nwebsite supported now:   hdwallpapers simpledesktop wallhaven"
esac